### ISSUE TITLE
Docker Config Files missing

### ISSUE THREAD

**Issue by jirevwe** [hackthievist/sterling-fixtures#1]
Hi hi,

You wrote:
- Copy the files docker-config/secrets.env.example, docker-config/config.env.example to docker-config/secrets.env, docker-config/config.env and substitute the settings to match your development environment.

However, the `docker-config` folder was added to `.gitignore`

**Comment by hackthievist** [comment]
Duly updated. The example files were not included. That has now been fixed.

**Comment by hackthievist** [comment]
> Hi hi,
> 
> You wrote:
> 
> * Copy the files docker-config/secrets.env.example, docker-config/config.env.example to docker-config/secrets.env, docker-config/config.env and substitute the settings to match your development environment.
> 
> However, the `docker-config` folder was added to `.gitignore`

Duly updated. The example files were not included. That has now been fixed.
